flibitijibibo/SDL2-CS

src/SDL2.cs
I needed these for a project, so I added bindings for them. Tested and working. The documenation is copied verbatin from SDL_power.h in SDL 2.0.4
While .NET does offer alternate ways to access this information, the methods to do so are in the System.Windows.Forms namespace, which is a heavy dependency to add for such a small feature.
=> Added bindings for SDL_PowerState and SDL_GetPowerInfo

src/SDL2.cs
Added an overload for SDL_UpdateTexture so that you can pass a null reference, which is allowed
by the SDL2 spec. Similar pattern already exists for SDL_RenderCopy
=> add SDL_UpdateTexture overload

src/SDL2.cs
Adds an overload to SDL_OpenAudio so that you can pass IntPtr.Zero for the obtained parameter, as allowed by the SDL2 spec.
=> overload openaudio to allow null

src/SDL2.cs
=> When a null C# string is passed to UTF8_ToNative(), return a null pointer instead of an empty C string.

SDL2-CS.csproj
Hi, I noticed the `optimize` flag was unset on Release configurations while I was messing with my build scripts and looked at msbuild outputs:
```
/optimize- /out:obj/Release/SDL2-CS.dll
```
I am unsure if it was left off intentionally lest something breaks, but nothing seems to be on fire on my end at the moment !
Even if it's a simple wrapper and I don't expect any performance improvements from that change at all, it's just standard for this flag to be set on Release builds :p
=> Enable the optimise flag in Release configurations

src/SDL2.cs
Add overload to SDL_GL_SetAttribute which accepts the SDL_GLprofile enum to prevent having to cast.
Before:
```csharp
SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 4);
SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 0);
SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, (int)SDL_GL_CONTEXT_PROFILE_CORE);
```
After:
```csharp
SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 4);
SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 0);
SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE);
```
I've got `using static`(s) at the top so the code looks more C like.
=> Add overload to SDL_GL_SetAttribute which accepts the SDL_GLprofile enum to prevent having to cast

gitlab-ci/SDL2-CS.nuspec, gitlab-ci/build-net461.sh, gitlab-ci/build-netcore.sh, gitlab-ci/deploy.sh, gitlab-ci/package.sh
Noticed the builds were `Debug`, so I changed that to `Release` and was also able to remove `sed` from the package script :tada:
=> Build in a release configuration before packaging.

src/SDL2.cs
I've left out `SDL_MessageBoxColorScheme` because I'm not sure how to fix it:
```
[StructLayout(LayoutKind.Sequential)]
public struct SDL_MessageBoxColorScheme
{
[MarshalAs(UnmanagedType.ByValArray, ArraySubType = UnmanagedType.Struct, SizeConst = (int)SDL_MessageBoxColorType.SDL_MESSAGEBOX_COLOR_MAX)]
public SDL_MessageBoxColor[] colors;
}
```
```
typedef struct
{
SDL_MessageBoxColor colors[SDL_MESSAGEBOX_COLOR_MAX];
} SDL_MessageBoxColorScheme;
```
Fixes #153
=> Remove obsolete unmanaged type

src/SDL2.cs
`VkSurfaceKHR` is defined by the macro `VK_DEFINE_NON_DISPATCHABLE_HANDLE`. This means, at least in the .NET world, that it's a ulong, not an IntPtr ([per the spec](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VK_DEFINE_NON_DISPATCHABLE_HANDLE.html)). This fixes a stack imbalance when using `SDL_Vulkan_CreateSurface`.
=> SDL_Vulkan_CreateSurface should use ulong

src/SDL2.cs
While working on a project of mine I noticed that SDL-CS is missing some functionality from SDL_cpuinfo.h that allows a developer to probe the capabilities of the CPU.
=> Added various CPU capability calls from SDL_cpuinfo.h

src/SDL2.cs
This simply updates the comment, seeing as the functionality was already added.
I checked both with my system package's native library and with FNA's native library archive, in both cases the event is triggered by default.
Hmm, that and the [documentation](https://wiki.libsdl.org/SDL_DropEvent?highlight=%28%5CbCategoryStruct%5Cb%29%7C%28CategoryEvents%29#Remarks) also states that:
> SDL_DropEvent is a member of the SDL_Event union and is used when an event of type SDL_DROPFILE, SDL_DROPTEXT, SDL_DROPBEGIN, or SDL_DROPCOMPLETE is reported. You would access it through the event's drop field.
>
>These events are enabled by default. You can disable it with SDL_EventState().
=> Drop events are actually enabled by default

src/SDL2.cs, src/SDL2_mixer.cs
As requested here are the RWops changes independently.
It adds some missing constants and functions.
The SDL_RWops structure was also partially added for use with Marshal or unsafe code along with callback signatures used by said structure.
It also exposes SDL_RWFromFile as public now, so several places in the code that referenced INTERNAL_SDL_RWFromFile(string, string) where changed to reflect that.
These changes were made as part of my personal SDLWrapper project when implementing the [ReadWriteOperation](https://github.com/JamesK89/SDLWrapper/blob/master/ReadWriteOperation.cs) class. I only mention it in case you need an example of how I used it in practice.
=> Added additional RWops functions and partial SDL_RWops structure.

src/SDL2.cs
What the titled said. This field was [added in SDL 2.0.6](https://wiki.libsdl.org/SDL_SysWMinfo).
HINSTANCE is needed for creating vulkan surfaces on Windows in [Veldrid](https://github.com/mellinoe/veldrid).
=> Add SDL_SysWMinfo.info.win.hinstance

src/SDL2.cs
Per [this comment](https://hg.libsdl.org/SDL/file/355a4f94a782/include/SDL_events.h#l588), the `SDL_Event` struct needs to be padded out to 56 bytes.
=> Add padding to SDL_Event

src/SDL2.cs
We need to not send garbage down to SDL when we get a null string.  The buffer would be sized 0, so it wouldn't be converted to an empty string like line 73 is trying to do.  The SDL API is designed to accept null as a valid argument, so best to pass it along preserving the API contract.
=> Fix buffer overflow.

src/SDL2_image.cs
When I was trying to setup a basic example using SDL2-CS I found that SDL2_image didn't have `IMG_GetError` and `IMG_SetError`. After some digging I then found out that the `SDL2_image.h` just has:
`/* We'll use SDL for reporting errors */`
`#define IMG_SetError    SDL_SetError`
`#define IMG_GetError    SDL_GetError`
So this PR provides the same functionality by just wrapping the `SDL_GetError` and `SDL_SetError` in SDL2.cs.
=> Added IMG_GetError and IMG_SetError

src/SDL2.cs
The `SDL_SetWindowDisplayMode` function [can be passed in `NULL`](https://wiki.libsdl.org/SDL_SetWindowDisplayMode) instead of a `SDL_DisplayMode` reference to use the window's dimensions and the desktop's format and refresh rate.
This overload is meant to be used with `IntPtr.Zero`.
=> Add NULL overload to SDL_SetWindowDisplayMode

src/SDL2.cs
This adds some missing overloads that Ryujinx uses.
Changelog:
- Add a new overload of ``SDL_MixAudioFormat`` to allow passing raw pointers as ``dest`` and ``src`` (useful for usage with ``SDL_AudioSpec``'s callback).
- Add a new overload of ``SDL_OpenAudioDevice`` to allow passing null for the ``device`` parameter.
- Add a new overload of ``SDL_Vulkan_GetInstanceExtensions`` to allow passing null for the ``pName`` parameter.
=> Add multiple missing pointer overloads

src/SDL2.cs
I forgot to do this when writing up the 2.0.16 changes. Noticed it because .NET 6 wasm yelled at me when trying to compile SDL2-CS.
=> Add missing EntryPoint for SDL_AndroidShowToast

src/SDL2_ttf.cs
Adding some missing functions to SDL2_ttf that are just wrappers of the `SDL_GetError` and `SDL_SetError` as per the SDL_ttf header:
```
/* We'll use SDL for reporting errors */
#define TTF_SetError    SDL_SetError
#define TTF_GetError    SDL_GetError
```
=> Add TTF_GetError and TTF_SetError

src/SDL2_mixer.cs
Adding `Mix_GetError`, `Mix_SetError`, `Mix_ClearError` as per the SDL_mixer header file:
/* We'll use SDL for reporting errors */
#define Mix_SetError    SDL_SetError
#define Mix_GetError    SDL_GetError
#define Mix_ClearError  SDL_ClearError
=> Add Mix_GetError, Mix_SetError, Mix_ClearError

Makefile, SDL2-CS.Core.csproj, SDL2-CS.csproj, src/SDL2_gfx.cs
Hello, this is a patch to add the SDL2_gfx library bindings to SDL2-CS, I think it could be quite useful to some people
My commit message already describe some stuff so let's try not to repeat it too much x)
This implements bindings for the 4 headers containing functions in them as well as the FPSmanager struct in SDL2_framerate.h (the remaining header only contains a long byte array for a font definition, I don't think it would be useful anyway and probably out of place in the library)
If someone wants to try this, you might need to change your SDL2_gfx library path (on a unix system at least) for the DllImports to work
=> SDL2_gfx library bindings

src/SDL2.cs
So no kludging with an array interop.
=> Add pointer overload for SDL_PeepEvents.

src/SDL2.cs
SDL source: https://github.com/libsdl-org/SDL/blob/580d231822b20b52ce36dfc2918b691cadf5ac84/include/SDL_touch.h#L98-L104.
Uses same convention as `SDL_JoystickName` etc.:
https://github.com/flibitijibibo/SDL2-CS/blob/dd7503d2acc21e9392d65a7d1cdb2fec4df19ee9/src/SDL2.cs#L6621-L6631
=> Add `SDL_GetTouchName`

src/SDL2.cs
Some of the newer events don't have the proper enum type set, all of the earlier events have it properly as `SDL_EventType type`.
=> Use proper `SDL_EventType` enum in all `SDL_*Event`s

src/SDL2.cs
This function should return an SDL_bool, not void per SDL wiki https://wiki.libsdl.org/SDL_HasARMSIMD. 
This will possibly have an effect on armv7 and early armv8 platforms so it's important it gets fixed.
=> SDL_HasARMSIMD should be SDL_bool return type

src/SDL2.cs
The documentation for [SDL_JoystickGetAxisInitialState](https://wiki.libsdl.org/SDL_JoystickGetAxisInitialState) and it's implementation is using a Sint16 for the state pointer, this has for some reason been translated to a ushort in C# which transforms the negative values into positive values. This didn't seem like the intended behaviour here so this goes and fix it
=> Fix the SDL_JoystickGetAxisInitialState signature

SDL2-CS.Core.csproj, src/SDL2.cs, src/SDL2_image.cs, src/SDL2_mixer.cs, src/SDL2_ttf.cs
This PR enables the trimming and AOT analyzers, and fixes all of the corresponding warnings. There were only a few to fix, and they were all fixed by using the generic versions of some marshalling functions.
Unfortunately, those functions were introduced in .NET 4.5.1, so I had to bump the minimum framework to that. Hopefully this shouldn't cause too much of a problem, since .NET 4.0 is already long out of support.
I also added .NET 7.0 as a target framework so that AOT warnings are displayed during compilation (but that can be removed if wanted).
=> Support trimming and AOT

src/SDL2.cs
This small PR exposes a few RWops functions, which allows callers to load and save from memory (e.g. embedded resources).
This way we could avoid writing to a file first in order to use the currently exposed functions which only take a file path.
For example, Ryujinx is currently making use of `SDL_LoadBMP_RW()` here: [SetWindowIcon()](https://github.com/TSRBerry/Ryujinx/blob/c1a78095aa5a9a4aaff81a3489cd819f119d98b0/Ryujinx.Headless.SDL2/WindowBase.cs#L117-L143)
(I edited this in Github's online editor, so I hope I didn't miss any of them.)
=> Publicly expose RWops functions

src/SDL2.cs
Added `SDL_GetWindowSizeInPixels` which is available from SDL 2.26.0, as `SDL_GL/Metal/Vulkan_GetDrawableSize()` were removed from SDL's main branch: https://github.com/libsdl-org/SDL/pull/7183
Link to the SDL_video header:
https://github.com/libsdl-org/SDL/blob/05eb08053d48fea9052ad02b3d619244aeb868d3/include/SDL_video.h#L1050-L1069
=> Add SDL_GetWindowSizeInPixels
